#!/bin/bash
set -e

echo ''
echo '__________._____.   .__  .__        __  .__                          '
echo '\______   \__\_ |__ |  | |__| _____/  |_|  |__   ____   ____ _____   '
echo ' |    |  _/  || __ \|  | |  |/  _ \   __\  |  \_/ __ \_/ ___\\__  \  '
echo ' |    |   \  || \_\ \  |_|  (  <_> )  | |   Y  \  ___/\  \___ / __ \_'
echo ' |______  /__||___  /____/__|\____/|__| |___|  /\___  >\___  >____  /'
echo '        \/        \/                         \/     \/     \/     \/ '
echo ''

echo "[MumukiDevstart::Bibliotheca] Ensuring node version..."
if [ $(cat .nvmrc) != $(node -v) ]; then
  echo "Unsupported node version. Please run nvm install first. Aborting"
  exit 1
fi

echo "[MumukiDevstart::Bibliotheca] Installing dependencies...."
npm install

echo "[MumukiDevstart::Bibliotheca] Starting server...."
npm start
