angular
  .module('editor')
  .constant('LANG_ES', {

    add_choice: 'Agregar alternativa',
    add_exercise: 'Agregar ejercicio',
    add_expectation: 'Agregar expectativa',
    authors: 'Autores',
    binding: 'Binding',
    blockquote: 'Cita',
    chapter: 'Capítulo',
    choices: 'Alternativas',
    code: 'Código',
    collaborators: 'Colaboradores',
    content: 'Contenido',
    corollary: 'Corolario',
    default_code: 'Código por defecto',
    description: 'Descripción',
    editor: 'Editor',
    english: 'Inglés',
    error_choices_empty_validation: '{{fullName}}: Tiene que ofrecer al menos dos alternativas',
    error_choices_incomplete_validation: '{{fullName}}: Tiene alternativas incompletas',
    error_editor_code_validation: '{{fullName}}: Debe tener al menos una prueba o una expectativa',
    error_editor_multiple_choice_validation: '{{fullName}}: Debe seleccionar al menos una alternativa',
    error_editor_single_choice_validation: '{{fullName}}: Debe seleccionar solamente una alternativa',
    error_editor_single_choice_validation2: '{{fullName}}: Debe seleccionar una alternativa como máximo',
    error_expectations_incomplete_validation: '{{fullName}}: Tiene expectativas incompletas',
    error_mandatory_field: '{{fullName}}: El campo "{{ field }}" no puede estar vacío',
    evaluation: 'Evaluación',
    exercise: 'Ejercicio',
    expectations: 'Expectativas',
    extra: 'Código extra',
    extra_code: 'Código extra',
    guide_saved_successfully: 'Guía guardada satisfactoriamente',
    guide: 'Guía',
    guides: 'Guías',
    hint: 'Pista',
    inspection: 'Inspección',
    item: 'Item',
    language: 'Lenguaje',
    learning: 'Aprendizaje',
    license_disclaimer: 'Esta guía será publicada bajo los términos de la <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">Licencia Creative Commons Compartir-Igual, 4.0</a>. Para aprender más sobre las Licencias Creative Commons visitá <a href="https://creativecommons.org/share-your-work">https://creativecommons.org/share-your-work</a>.',
    link: 'Link',
    locale: 'Idioma',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    name: 'Nombre',
    negated: 'Negado',
    new_exercise: 'Nuevo ejercicio',
    new_guide: 'Nueva guía',
    object: 'Objeto',
    organization: 'Organización',
    placeholder_authors: '...Ingrese los autores...',
    placeholder_collaborators: '...Ingrese los colaboradores...',
    placeholder_corollary: '...Ingrese el corolario...',
    placeholder_default_code: '...Ingrese el código por defecto...',
    placeholder_description: '...Ingrese la descripción...',
    placeholder_exercise_name: '...Nombre del ejercicio...',
    placeholder_extra_code: '...Ingrese el código extra...',
    placeholder_guide_name: '...Nombre de la guía...',
    placeholder_hint: '...Ingrese la pista...',
    placeholder_solution: '...Ingrese la solución a probar...',
    placeholder_teacher_info: '...Ingrese la información del docente...',
    placeholder_test: '...Ingrese las pruebas...',
    placeholder_undefined: '',
    practice: 'Práctica',
    remove: 'Remover',
    search: 'Buscar',
    solution: 'Solución',
    spanish: 'Español',
    subject: 'Sujeto',
    submit: 'Enviar',
    teacher_info: 'Información del docente',
    test: 'Pruebas',
    text: 'Texto',
    tooltip_bold: 'Negrita (ctrl+b)',
    tooltip_code: 'Código',
    tooltip_image: 'Imagen',
    tooltip_inline_code: 'Código en línea',
    tooltip_italic: 'Cursiva (ctrl+i)',
    tooltip_link: 'Link (ctrl+k)',
    tooltip_mumuki: 'Mumuki (ctrl+m)',
    tooltip_ol: 'Lista ordenada',
    tooltip_quote: 'Cita',
    tooltip_ul: 'Lista desordenada',
    transitive: 'Transitivo',
    type: 'Tipo',
    verb: 'Verbo',

  });
