angular
  .module('editor')
  .constant('LANG_EN', {

    add_choice: 'Add choice',
    add_exercise: 'Add exercise',
    add_expectation: 'Add expectation',
    add_expectation_inspection: 'Add inspection',
    add_expectation_smell: 'Exclude smell',
    appendix: 'Appendix',
    authors: 'Authors',
    binding: 'Scope',
    blockquote: 'Blockquote',
    book: 'Book',
    book_saved_successfully: 'Book saved successfully',
    books: 'Books',
    chapter: 'Chapter',
    choices: 'Choices',
    code: 'Code',
    code_smells: 'Code Smells',
    collaborators: 'Credits',
    complements: 'Complements',
    content: 'Content',
    corollary: 'Corollary',
    default_content: 'Default code',
    description: 'Description',
    details: 'View details',
    editor: 'Editor',
    editor_type: 'Editor type',
    english: 'English (UK)',
    error_choices_empty_validation: '{{fullName}}: Should have at least two choices',
    error_choices_incomplete_validation: '{{fullName}}: Has incomplete choices',
    error_editor_code_validation: '{{fullName}}: Should have at least one test or expectation',
    error_editor_hidden_validation: '{{fullName}}: Should have at least one test',
    error_editor_multiple_choice_validation: '{{fullName}}: Should have at least one choice selected',
    error_editor_single_choice_validation_no_selected: '{{fullName}}: Should not have choices selected',
    error_editor_single_choice_validation_only_one: '{{fullName}}: Shoud have only one choice selected',
    error_expectations_incomplete_validation: '{{fullName}}: Has incomplete expectations',
    error_mandatory_field: '{{ fullName }}: Field {{ field }} is mandatory',
    errored: "Oops, your solution doesn't work",
    evaluation: 'Evaluation',
    exercise: 'Exercise',
    exercise_done: 'All our tests passed!',
    exercise_type: 'Exercise type',
    expectations: 'Expectations',
    extra: 'Extra code',
    extra_code: 'Extra code',
    extra_visible: 'Show extra code',
    failed: 'Oops, something went wrong',
    guide: 'Guide',
    guide_type: 'Guide type',
    guide_saved_successfully: 'Guide saved successfully',
    guides: 'Guides',
    hidden: 'Hidden',
    hint: 'Hint',
    inspection: 'Inspection',
    inspections: 'Inspections',
    item: 'Item',
    language: 'Language',
    layout: 'Editor layout',
    learning: 'Learning',
    leave_current_item_with_changes: 'Are you sure? all changes will be lost',
    lesson: 'Lesson',
    license_disclaimer: 'This guide will be published under <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">Creative Commons Attribution-ShareAlike 4.0 International Public License</a>. To learn more about Creative Commons Licenses visit <a href="https://creativecommons.org/share-your-work">https://creativecommons.org/share-your-work</a>.',
    link: 'Link',
    locale: 'Locale',
    login: 'Log in',
    logout: 'Log out',
    multiple_choice: 'Multiple choice',
    name: 'Name',
    negated: 'Negated',
    new_book: 'New book',
    new_exercise: 'New exercise',
    new_guide: 'New guide',
    new_topic: 'New topic',
    no: 'No',
    object: 'Object',
    organization: 'Organization',
    passed: 'All right',
    passed_with_warnings: 'It worked, but you can do better',
    placeholder_add_chapter: 'Add chapter',
    placeholder_add_complement: 'Add complement',
    placeholder_add_lesson: 'Add lesson',
    placeholder_appendix: '...Enter appendix...',
    placeholder_authors: '...Full Name...',
    placeholder_book_name: '...Book name...',
    placeholder_collaborators: '...Enter credits...',
    placeholder_corollary: '...Enter corollary...',
    placeholder_default_content: '...Enter default content...',
    placeholder_description: '...Enter description...',
    placeholder_exercise_name: '...Exercise name...',
    placeholder_extra_code: '...Enter extra code...',
    placeholder_guide_name: '...Guide name...',
    placeholder_hint: '...Enter hint...',
    placeholder_solution: '...Enter solution to test...',
    placeholder_teacher_info: '...Enter teacher info...',
    placeholder_test: '...Enter tests...',
    placeholder_topic_name: '...Topic name...',
    placeholder_undefined: '',
    playground: 'Playground',
    practice: 'Practice',
    problem: 'Problem',
    reading: 'Reading',
    remove: 'Remove',
    save: 'Save',
    search: 'Search',
    saving: 'Saving...',
    single_choice: 'Single choice',
    solution: 'Solution',
    spanish: 'Spanish (Arg)',
    subject: 'Subject',
    submit: 'Submit',
    target: 'Subject',
    teacher_info: 'Teacher information',
    test: 'Tests',
    test_results: 'Tests results',
    text: 'Text',
    tooltip_bold: 'Bold (ctrl+b)',
    tooltip_code: 'Code',
    tooltip_emojis: 'Emojis',
    tooltip_image: 'Image',
    tooltip_inline_code: 'Inline code',
    tooltip_italic: 'Italic (ctrl+i)',
    tooltip_link: 'Link (ctrl+k)',
    tooltip_mumuki: 'Mumuki (ctrl+m)',
    tooltip_ol: 'Ordered list',
    tooltip_quote: 'Quote',
    tooltip_ul: 'Unordered List',
    topic: 'Topic',
    topic_saved_successfully: 'Topic saved successfully',
    topics: 'Topics',
    transitive: 'Transitive',
    type: 'Type',
    unmeet_expectations: 'Goals that weren\'t met',
    upload: 'Upload file',
    verb: 'Verb',
    yes: 'Yes',

  });
