angular
  .module('editor')
  .constant('LANG_EN', {

    add_choice: 'Add choice',
    add_expectation: 'Add expectation',
    authors: 'Authors',
    authors_placeholder: '...Full Name...',
    binding: 'Binding',
    blockquote: 'Blockquote',
    choices: 'Choices',
    code: 'Code',
    collaborators: 'Collaborators',
    collaborators_placeholder: '...Enter collaborators...',
    content: 'Content',
    corollary: 'Corollary',
    corollary_placeholder: '...Enter corollary...',
    default_code: 'Default code',
    description: 'Description',
    description_placeholder: '...Enter description...',
    editor: 'Editor',
    english: 'English',
    evaluation: 'Evaluation',
    exercise: 'Exercise',
    expectations: 'Expectations',
    extra: 'Extra code',
    extra_code: 'Extra code',
    extra_code_placeholder: '...Enter extra code...',
    guide_name_placeholder: '...Guide name...',
    guides: 'Guides',
    hint: 'Hint',
    hint_placeholder: '...Enter hint...',
    inspection: 'Inspection',
    item: 'Item',
    language: 'Language',
    license_disclaimer: 'This guide will be published under <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">Creative Commons Attribution-ShareAlike 4.0 International Public License</a>. To learn more about Creative Commons Licenses visit <a href="https://creativecommons.org/share-your-work">https://creativecommons.org/share-your-work</a>.',
    link: 'Link',
    login: 'Log in',
    logout: 'Log out',
    negated: 'Negated',
    object: 'Object',
    remove: 'Remove',
    search: 'Search',
    solution: 'Solution',
    spanish: 'Spanish',
    subject: 'Subject',
    submit: 'Submit',
    teacher_info: 'Teacher information',
    teacher_info_placeholder: '...Enter teacher info...',
    test: 'Tests',
    text: 'Text',
    transitive: 'Transitive',
    undefined_placeholder: '',
    verb: 'Verb',

  });
