angular
  .module('editor')
  .constant('LANG_ES', {

    add_choice: 'Agregar opción',
    add_exercise: 'Agregar ejercicio',
    add_expectation: 'Agregar expectativa',
    authors: 'Autores',
    binding: 'Binding',
    blockquote: 'Cita',
    book: 'Libro',
    book_saved_successfully: 'Libro guardado satisfactoriamente',
    books: 'Libros',
    chapter: 'Capítulo',
    choices: 'Opciones',
    code: 'Código',
    collaborators: 'Colaboradores',
    complements: 'Complementos',
    content: 'Contenido',
    corollary: 'Corolario',
    default_content: 'Código por defecto',
    description: 'Descripción',
    editor: 'Editor',
    editor_type: 'Tipo de editor',
    english: 'Inglés (UK)',
    error_choices_empty_validation: '{{fullName}}: Tiene que ofrecer al menos dos opción',
    error_choices_incomplete_validation: '{{fullName}}: Tiene opción incompletas',
    error_editor_code_validation: '{{fullName}}: Debe tener al menos una prueba o una expectativa',
    error_editor_hidden_validation: '{{fullName}}: Debe tener al menos una prueba',
    error_editor_multiple_choice_validation: '{{fullName}}: Debe seleccionar al menos una opción',
    error_editor_single_choice_validation2: '{{fullName}}: Debe seleccionar una opción como máximo',
    error_editor_single_choice_validation: '{{fullName}}: Debe seleccionar solamente una opción',
    error_expectations_incomplete_validation: '{{fullName}}: Tiene expectativas incompletas',
    error_mandatory_field: '{{fullName}}: El campo "{{ field }}" no puede estar vacío',
    evaluation: 'Evaluación',
    exercise: 'Ejercicio',
    exercise_type: 'Tipo de ejercicio',
    expectations: 'Expectativas',
    extra: 'Código extra',
    extra_code: 'Código extra',
    extra_visible: 'Mostrar código extra',
    guide: 'Guía',
    guide_type: 'Tipo de guía',
    guide_saved_successfully: 'Guía guardada satisfactoriamente',
    guides: 'Guías',
    hidden: 'Oculto',
    hint: 'Pista',
    inspection: 'Inspección',
    item: 'Item',
    language: 'Lenguaje',
    layout: 'Disposición del editor',
    learning: 'Aprendizaje',
    leave_current_item_with_changes: 'Tenés cambios sin publicar, que se perderán si abandonás esta pantalla. ¿Querés continuar?',
    lesson: 'Lección',
    license_disclaimer: 'Esta guía será publicada bajo los términos de la <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode">Licencia Creative Commons Compartir-Igual, 4.0</a>. Para aprender más sobre las Licencias Creative Commons visitá <a href="https://creativecommons.org/share-your-work">https://creativecommons.org/share-your-work</a>.',
    link: 'Link',
    locale: 'Idioma',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    multiple_choice: 'Selección múltiple',
    name: 'Nombre',
    negated: 'Negado',
    new_book: 'Nuevo libro',
    new_exercise: 'Nuevo ejercicio',
    new_guide: 'Nueva guía',
    new_topic: 'Nuevo Tema',
    no: 'No',
    object: 'Objeto',
    organization: 'Organización',
    placeholder_add_chapter: 'Agregar capítulo',
    placeholder_add_complement: 'Agregar complemento',
    placeholder_add_lesson: 'Agregar lección',
    placeholder_authors: '...Ingrese los autores...',
    placeholder_book_name: '...Nombre del libro...',
    placeholder_collaborators: '...Ingrese los colaboradores...',
    placeholder_corollary: '...Ingrese el corolario...',
    placeholder_default_content: '...Ingrese el código por defecto...',
    placeholder_description: '...Ingrese la descripción...',
    placeholder_exercise_name: '...Nombre del ejercicio...',
    placeholder_extra_code: '...Ingrese el código extra...',
    placeholder_guide_name: '...Nombre de la guía...',
    placeholder_hint: '...Ingrese la pista...',
    placeholder_solution: '...Ingrese la solución a probar...',
    placeholder_teacher_info: '...Ingrese la información del docente...',
    placeholder_test: '...Ingrese las pruebas...',
    placeholder_topic_name: '...Nombre del tema...',
    placeholder_undefined: '',
    playground: 'Juego',
    practice: 'Práctica',
    problem: 'Problema',
    remove: 'Remover',
    search: 'Buscar',
    single_choice: 'Selección única',
    solution: 'Solución',
    spanish: 'Español (Arg)',
    subject: 'Sujeto',
    submit: 'Enviar',
    teacher_info: 'Información del docente',
    test: 'Pruebas',
    text: 'Texto',
    tooltip_bold: 'Negrita (ctrl+b)',
    tooltip_code: 'Código',
    tooltip_image: 'Imagen',
    tooltip_inline_code: 'Código en línea',
    tooltip_italic: 'Cursiva (ctrl+i)',
    tooltip_link: 'Link (ctrl+k)',
    tooltip_mumuki: 'Mumuki (ctrl+m)',
    tooltip_ol: 'Lista ordenada',
    tooltip_quote: 'Cita',
    tooltip_ul: 'Lista desordenada',
    topic: 'Tema',
    topic_saved_successfully: 'Tema guardado satisfactoriamente',
    topics: 'Temas',
    transitive: 'Transitivo',
    type: 'Tipo',
    verb: 'Verbo',
    yes: 'Sí',

  });
